# Generated by Django 3.2.15 on 2022-09-28 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrontPage',
        ),
    ]
