# Generated by Django 3.2.15 on 2022-10-02 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
