# Generated by Django 3.2.15 on 2022-10-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_delete_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
